from pydantic import BaseModel, Field
from typing import List, Dict

class CampaignProposal(BaseModel):
    """Structured campaign suggestion from the Merchant Campaign Agent (AG-001)."""
    campaign_name: str = Field(description="Catchy name for the campaign.")
    suggested_budget: float = Field(description="Recommended budget for this campaign based on goals and category.")
    suggested_duration_days: int = Field(description="Recommended number of days for the campaign.")
    offer_value: float = Field(description="Recommended cashback percentage (e.g. 10.0 for 10% cashback).")
    target_segments: List[str] = Field(description="Behavioral or spend target segments, e.g., 'Coffee Buyers', 'Frequent Diners'.")
    marketing_copy: str = Field(description="Engaging marketing text designed for the consumer offer feed.")
    suggested_legal_disclosure: str = Field(description="Legal rules, e.g., 'Valid on debit card transactions. Minimum spend $10. Max cashback $5.'")
    reasoning: str = Field(description="AI explanation for why this campaign fits the merchant's history and goals.")


class ComplianceReview(BaseModel):
    """Structured compliance analysis from the Compliance Agent (AG-008)."""
    is_compliant: bool = Field(description="True if the campaign complies with guidelines, False if it has violations.")
    flagged_reasons: List[str] = Field(default=[], description="Reasons for compliance failure or warnings.")
    restricted_categories_found: List[str] = Field(default=[], description="Any restricted business categories detected (e.g. gambling, alcohol, high-risk).")
    disclosures_required: List[str] = Field(default=[], description="Additional disclosures or edits needed to be legally compliant.")
    suggested_copy_edits: str = Field(default="", description="Rewritten copy that solves the compliance issues while retaining marketing value.")


class CategoryAffinity(BaseModel):
    """Single category affinity score."""
    category: str = Field(description="Category name (e.g., Dining, Coffee, Retail, Fitness, Travel).")
    score: float = Field(description="Affinity score between 0.0 (no affinity) and 10.0 (high affinity).")
    reasoning: str = Field(description="Explanation based on customer transaction counts, sizes, or trends.")


class CustomerAffinityProfile(BaseModel):
    """Full affinity breakdown for a customer by Customer Affinity Agent (AG-003)."""
    customer_id: str = Field(description="ID of the customer analyzed.")
    affinities: List[CategoryAffinity] = Field(description="List of calculated category affinities.")
    dominant_segment: str = Field(description="Highest affinity segment identified for this customer.")


class RankedOfferItem(BaseModel):
    """Details of a single ranked offer in the consumer feed."""
    campaign_id: str = Field(description="ID of the candidate campaign.")
    score: float = Field(description="Ranking score (0.0 to 10.0) based on customer profile fit.")
    reason_for_ranking: str = Field(description="Internal reasoning for this specific ranking position.")
    user_explanation: str = Field(description="Customer-facing explanation of why this offer was shown (AG-010).")


class RankedOffers(BaseModel):
    """Ranked candidate list of offers generated by the Offer Ranking Agent (AG-006)."""
    customer_id: str = Field(description="ID of the customer.")
    ranked_offers: List[RankedOfferItem] = Field(description="Offers ordered from highest relevance to lowest.")
